"""
Converts the MODIS fire-frequency raster (`10_modis_fire_frequency_2001_2024.tif`,
generated by `02_export_modis_fire_frequency.py`) into a polygon vector layer -- the
"burned areas, averaged over 2001-2024, MODIS case" requested as a vector deliverable
instead of a raster.

What "averaged over 2001-2024" means here, spatially: each polygon is a patch of
contiguous pixels that share the exact same fire-frequency value (years burned out of the
24, 2001-2024, from MODIS/061/MCD64A1 -- same source/definition as the raster it comes
from). The polygon's `avg_freq` field is that count divided by 24, i.e. "on average, this
patch burned in this fraction of the years 2001-2024" -- the direct vector counterpart of
a per-pixel average. Only burned patches are kept (years_burned > 0); the never-burned
majority of the nucleus is dropped instead of exported as one giant polygon.

Field names are truncated to Shapefile's 10-character limit:
    yrs_burned  (int)   -- years burned out of 24, 2001-2024
    avg_freq    (float) -- yrs_burned / 24
    area_ha     (float) -- geodesic area in hectares (computed with pyproj.Geod, so it's
                            accurate regardless of the source CRS being geographic)

Re-run: "C:\\Users\\Natal\\.conda\\envs\\fire_thesis\\python.exe" 03_polygonize_modis_fire_frequency.py
"""

from pathlib import Path

import geopandas as gpd
import numpy as np
import rasterio
import rasterio.features
from pyproj import Geod
from shapely.geometry import shape

HERE = Path(__file__).parent
SRC_TIF = HERE / "10_modis_fire_frequency_2001_2024.tif"
OUT_SHP = HERE / "11_modis_fire_frequency_2001_2024_polygons.shp"

YEARS_IN_PERIOD = 24  # 2001-2024 inclusive
GEOD = Geod(ellps="WGS84")


def main() -> None:
    with rasterio.open(SRC_TIF) as src:
        freq = src.read(1)
        transform = src.transform
        crs = src.crs
        nodata = src.nodata

    burned_mask = (freq != nodata) & (freq > 0)
    freq_int = freq.astype(np.int32)

    records = []
    for geom, value in rasterio.features.shapes(freq_int, mask=burned_mask, transform=transform):
        records.append({"yrs_burned": int(value), "geometry": shape(geom)})

    gdf = gpd.GeoDataFrame(records, crs=crs)
    gdf["avg_freq"] = gdf["yrs_burned"] / YEARS_IN_PERIOD

    def geodesic_area_ha(geom) -> float:
        area_m2, _ = GEOD.geometry_area_perimeter(geom)
        return abs(area_m2) / 10_000

    gdf["area_ha"] = gdf["geometry"].apply(geodesic_area_ha)

    gdf = gdf[["yrs_burned", "avg_freq", "area_ha", "geometry"]]
    gdf.to_file(OUT_SHP, driver="ESRI Shapefile")

    print(f"Guardado: {OUT_SHP}")
    print(f"Poligonos: {len(gdf):,}")
    print(f"Area quemada total (>=1 anio en 2001-2024): {gdf['area_ha'].sum():,.1f} ha")
    print(gdf["yrs_burned"].describe())


if __name__ == "__main__":
    main()
